// Backend/orchestrator/disclaimer.js
// Single source of truth for disclaimer text and versioning.
// EU AI Act Art. 13 (transparency), legal domain non-advice requirement.
//
// ENFORCEMENT RULE: every analysis result that leaves the orchestrator MUST
// carry the disclaimer. enforceDisclaimer() guarantees this — call it on every
// parsed result before returning to the service layer.

const DISCLAIMER_VERSION = 'v1.0';

const DISCLAIMER_FR = `⚠️ AVERTISSEMENT LÉGAL : Cette analyse est générée par une intelligence artificielle à titre informatif uniquement. Elle ne constitue pas un avis juridique professionnel et ne saurait remplacer la consultation d'un avocat ou d'un juriste qualifié. TransparAI n'est pas un cabinet d'avocats. Les résultats peuvent contenir des inexactitudes. Vérifiez toujours les clauses importantes avec un professionnel du droit avant de signer tout contrat.`;

const DISCLAIMER_EN = `⚠️ LEGAL DISCLAIMER: This analysis is generated by artificial intelligence for informational purposes only. It does not constitute professional legal advice and cannot replace consultation with a qualified lawyer. TransparAI is not a law firm. Results may contain inaccuracies. Always verify important clauses with a legal professional before signing any contract.`;

const AI_DISCLOSURE_FR = `Analyse réalisée par IA (modèle : {model}) — droit applicable : France / UE`;

/**
 * Enforce that an analysis result carries the mandatory legal disclaimer.
 *
 * Appends the disclaimer as the final item in `clauses[]` if it is not already
 * present. This ensures the disclaimer is surfaced to the user in the clauses
 * list regardless of which code path produced the result (direct, chunked, or
 * cached).
 *
 * Also injects the disclaimer as a `legalDisclaimer` field on the result
 * object so the frontend can render it in a dedicated UI component.
 *
 * @param {object} result  Mutable result object { resume, score, clauses, ... }
 * @returns {object}       The same object, mutated in-place
 */
const enforceDisclaimer = (result) => {
  if (!result) return result;

  // Attach disclaimer text field — always present for frontend rendering
  result.legalDisclaimer = DISCLAIMER_FR;
  result.disclaimerVersion = DISCLAIMER_VERSION;

  // Append to clauses if not already included (idempotent)
  if (Array.isArray(result.clauses)) {
    const alreadyPresent = result.clauses.some(
      (c) => typeof c === 'string' && c.includes('intelligence artificielle'),
    );
    if (!alreadyPresent) {
      result.clauses.push(`ℹ️ ${DISCLAIMER_FR}`);
    }
  }

  return result;
};

module.exports = {
  DISCLAIMER_VERSION,
  DISCLAIMER_FR,
  DISCLAIMER_EN,
  AI_DISCLOSURE_FR,
  enforceDisclaimer,
};
